---

variables:
  BUNDLE: "bundle"
  REPO: "./docker"
  TAG: '0.1'
  IMG_REPO: 'harbor.httpsec.eu'

stages:
  - build

Build Rego package:
  stage: build
  image: ${IMG_REPO}/security/opa-build:0.1
  script:
    - cd ${REPO}
    - opa build --bundle --output ${BUNDLE}.tar.gz .
    - echo '{}' > manifest.conf
    - |
      oras push ${IMG_REPO}/docker-opa/${BUNDLE}:${TAG} \
        --config manifest.conf:application/vnd.oci.image.config.v1+json \
        ${BUNDLE}.tar.gz:application/vnd.oci.image.layer.v1.tar+gzip
  artifacts:
    name: "bundles"
    paths:
      - ${REPO}/${BUNDLE}.tar.gz
  when: manual
